@startuml
<style>
element {
    FontName Arial
}
</style>
class UserParams {
    + Name: string
    + Password: string
}
class User {
    + Id: int
    + Name: string
    + PasswordHash: string
}
class UserController {
    + CreateUser(newUser: UserParams)
    + Login(userParams: UserParams): string
    - GenerateJWT(user: User): string
}
interface IUserRepository {
    + CreateUser(name: string, password: string): User
    + GetUser(name: string): User?
    + VerifyPassword(user: User, password: string): bool
}

UserController --> IUserRepository
IUserRepository <|-- UserRepository
@enduml
