@startuml
[Frontend]
package "REST-API" as API {
  [Schachengine]
  [Eroeffnungen]
  [Nutzerdaten]
  [Statistiken]
}
[UCI-Engine] as uci
database Eroeffnungsbuch as buch
database "SQL-Datenbank" as sql

Frontend --> API
API --> Schachengine
API --> Eroeffnungen
API --> Nutzerdaten
API --> Statistiken

Schachengine --> uci
Eroeffnungen --> buch
Nutzerdaten --> sql
Statistiken --> sql

@enduml
