@startuml
[Frontend]
package "REST-API" as API {
  [Schachengine]
  [Eroeffnungen]
  [Authentifizierung]
  [Statistiken]
}
[UCI-Engine] as uci
database Eroeffnungsliste as liste
database "SQL-Datenbank" as sql

Frontend --> API
API --> Schachengine
API --> Eroeffnungen
API --> Authentifizierung
API --> Statistiken

Schachengine --> uci
Eroeffnungen --> liste
Authentifizierung --> sql
Statistiken --> sql

@enduml
