@startuml
<style>
element {
    FontName Arial
}
</style>
agent "Reverse Proxy (nginx)" as proxy
node Frontend
node "Rest-API" as API
database Postgres

proxy --> Frontend
proxy --> API
Frontend -> API

API --> Postgres

@enduml
