@startuml
<style>
element {
    FontName Arial
}
</style>
class OpeningOverview {
    + Id: string,
    + Name: string
}
class OpeningMove {
    + Name: string,
    + Move: string
}
class Opening {
    + Id: string
    + Name: string
    + Moves: string
    + IsRoot(): bool
    + IsInFamily(familyName: string): bool
    + NextMove(previousMoves: string): string
}
class OpeningController {
    + GetOpenings(): [OpeningOverview]
    + GetVariants(id: string): [OpeningOverview]
    + GetMoveVariants(id: string, played: string): [OpeningMove]
    + GetNextMove(id: string, played: string): OpeningMove
}
interface IOpeningRepository {
    + GetRootOpenings(): [Opening]
    + GetOpening(id: string): Opening?
    + GetVariants(id: string): [Opening]
    + GetOpeningsWithPlayedMoves(id: string, played: string): [Opening]
}
Interface IOpeningReader {
    + Read(): [Opening]
}


OpeningController --> IOpeningRepository
IOpeningRepository <|-- OpeningRepository
OpeningRepository --> IOpeningReader
IOpeningReader <|-- OpeningReaderTSV
@enduml
