@startuml
<style>
element {
    FontName Arial
}
</style>
class TrainingResult {
    + Id: int
    + UserId: int
    + User: User
    + OpeningId: string
    + Errors: int
    + Hints: int
    + DateTime: DateTime
}
class OpeningStatistics {
    + OpeningId: string
    + OpeningName: string
    + Expertise: double
    + PerfectRuns: int
    + HintedRuns: int
    + FailedRuns: int
    + TotalRuns: int
    + AvgErrors: double
    + AvgHints: double
}
class NewTrainingResult {
    VariantId: string
    Errors: int
    Hints: int
}
class StatisticsController {
    + AddTrainingResult(newTrainingResult: NewTrainingResult)
    + GetVariantStatistics(variantId: string): OpeningStatistics
    + GetStatistics(): [OpeningStatistics]
}
interface IStatisticsRepository {
    + CreateTrainingResult(trainingResult: TrainingResult)
    + GetVariantStatistics(userId: int, openingId: string): OpeningStatistics
    + GetStatistics(userId: int): [OpeningStatistics]
}
class StatisticsRepository {
    - calculateExpertise(totalRuns: int, failedRuns: int, hintedRuns: int,\n\tperfectRuns: int, lastDate: DateTime): double
}

StatisticsController --> IStatisticsRepository
IStatisticsRepository <|-- StatisticsRepository
@enduml
